// Code generated by goray. DO NOT EDIT.
//
// This file was generated by goray.
// It contains wrappers for the ray tasks and actors in this package.
//
// To regenerate this file, run:
//
//	goraygen <package-path>
package cases

import (
	"time"
	"unsafe"

	"github.com/ray4go/go-ray/ray"
	. "github.com/ray4go/go-ray/ray/generic"
)

// original task: [TestTask.ProcessCustomTypes]
func ProcessCustomTypes[CustomInt_0 _T0, CustomString_1 _T1, CustomSlice_2 _T2](ci CustomInt_0, cs CustomString_1, csl CustomSlice_2) *RemoteFunc[*Future3[CustomInt, CustomString, CustomSlice]] {
	return NewRemoteFunc[*Future3[CustomInt, CustomString, CustomSlice]]("ProcessCustomTypes", []any{ci, cs, csl})
}

// Test time.Time and other standard library types
// original task: [TestTask.ProcessTimeAndDuration]
func ProcessTimeAndDuration[time_Time_0 _T3, time_Duration_1 _T4](t time_Time_0, d time_Duration_1) *RemoteFunc[*Future2[time.Time, time.Duration]] {
	return NewRemoteFunc[*Future2[time.Time, time.Duration]]("ProcessTimeAndDuration", []any{t, d})
}

// original task: [TestTask.ProcessNestedStructs]
func ProcessNestedStructs[OuterStruct_0 _T5](outer OuterStruct_0) *RemoteFunc[*Future1[OuterStruct]] {
	return NewRemoteFunc[*Future1[OuterStruct]]("ProcessNestedStructs", []any{outer})
}

// Test deeply nested maps and slices
// original task: [TestTask.ProcessNestedCollections]
func ProcessNestedCollections[mapstringTomapstringint_0 _T6, sliceOfsliceOfstring_1 _T7, mapstringTosliceOfint_2 _T8](nestedMap mapstringTomapstringint_0, nestedSlice sliceOfsliceOfstring_1, mixedStructure mapstringTosliceOfint_2) *RemoteFunc[*Future3[map[string]map[string]int, [][]string, map[string][]int]] {
	return NewRemoteFunc[*Future3[map[string]map[string]int, [][]string, map[string][]int]]("ProcessNestedCollections", []any{nestedMap, nestedSlice, mixedStructure})
}

// Test variadic functions
// original task: [TestTask.ProcessVariadic]
func ProcessVariadic[int_0 _T9, int_1 _T9](base int_0, values ...int_1) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("ProcessVariadic", ExpandArgs([]any{base}, values))
}

// Test multiple return values with different types
// original task: [TestTask.MultipleReturnTypes]
func MultipleReturnTypes() *RemoteFunc[*Future6[int, string, []int, map[string]int, bool, *int]] {
	return NewRemoteFunc[*Future6[int, string, []int, map[string]int, bool, *int]]("MultipleReturnTypes", []any{})
}

// Test slice of interface{}
// original task: [TestTask.TaskWithSliceOfInterface]
func TaskWithSliceOfInterface[sliceOfany_0 _T10](data sliceOfany_0) *RemoteFunc[*Future1[[]interface{}]] {
	return NewRemoteFunc[*Future1[[]interface{}]]("TaskWithSliceOfInterface", []any{data})
}

// Test map with interface{} values
// original task: [TestTask.TaskWithMapOfInterface]
func TaskWithMapOfInterface[mapstringToany_0 _T11](data mapstringToany_0) *RemoteFunc[*Future1[map[string]interface{}]] {
	return NewRemoteFunc[*Future1[map[string]interface{}]]("TaskWithMapOfInterface", []any{data})
}

// original task: [TestTask.TaskWithDeeplyNestedInterface]
func TaskWithDeeplyNestedInterface[DeeplyNestedStruct_0 _T12](s DeeplyNestedStruct_0) *RemoteFunc[*Future1[DeeplyNestedStruct]] {
	return NewRemoteFunc[*Future1[DeeplyNestedStruct]]("TaskWithDeeplyNestedInterface", []any{s})
}

// original task: [TestTask.ProcessLargeStruct]
func ProcessLargeStruct[LargeStruct_0 _T13](large LargeStruct_0) *RemoteFunc[*Future1[LargeStruct]] {
	return NewRemoteFunc[*Future1[LargeStruct]]("ProcessLargeStruct", []any{large})
}

// Task for testing CallPythonCode
// original task: [TestTask.GetPythonEnvironment]
func GetPythonEnvironment() *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("GetPythonEnvironment", []any{})
}

// Tasks for testing advanced Wait scenarios
// original task: [TestTask.VariableDelayTask]
func VariableDelayTask[int_0 _T9, int_1 _T9](taskId int_0, delayMs int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("VariableDelayTask", []any{taskId, delayMs})
}

// original task: [TestTask.RandomFailureTask]
func RandomFailureTask[int_0 _T9, bool_1 _T14](taskId int_0, shouldFail bool_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("RandomFailureTask", []any{taskId, shouldFail})
}

// Task for testing ObjectRef edge cases
// original task: [TestTask.ReturnComplexObjectRef]
func ReturnComplexObjectRef() *RemoteFunc[*Future1[map[string]interface{}]] {
	return NewRemoteFunc[*Future1[map[string]interface{}]]("ReturnComplexObjectRef", []any{})
}

// original task: [TestTask.ProcessComplexObjectRef]
func ProcessComplexObjectRef[mapstringToany_0 _T11](obj mapstringToany_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("ProcessComplexObjectRef", []any{obj})
}

// Tasks for testing various option combinations
// original task: [TestTask.TaskWithAllOptions]
func TaskWithAllOptions[int_0 _T9](value int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("TaskWithAllOptions", []any{value})
}

// original task: [TestTask.LongRunningTask]
func LongRunningTask[int_0 _T9, string_1 _T15](duration int_0, value string_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("LongRunningTask", []any{duration, value})
}

// Tasks for testing edge cases with various data types
// original task: [TestTask.ProcessMixedTypes]
func ProcessMixedTypes[int_0 _T9, float64_1 _T16, string_2 _T15, bool_3 _T14, sliceOfstring_4 _T17, mapstringToint_5 _T18](intVal int_0, floatVal float64_1, stringVal string_2, boolVal bool_3, sliceVal sliceOfstring_4, mapVal mapstringToint_5) *RemoteFunc[*Future1[map[string]interface{}]] {
	return NewRemoteFunc[*Future1[map[string]interface{}]]("ProcessMixedTypes", []any{intVal, floatVal, stringVal, boolVal, sliceVal, mapVal})
}

// 返回剩余 step 后的 hostname 列表
// original task: [TestTask.ChainCall]
func ChainCall[sliceOfstring_0 _T17, int_1 _T9, int_2 _T9, bool_3 _T14](nodeIds sliceOfstring_0, currIdx int_1, remainStep int_2, cross bool_3) *RemoteFunc[*Future1[map[string]struct{}]] {
	return NewRemoteFunc[*Future1[map[string]struct{}]]("ChainCall", []any{nodeIds, currIdx, remainStep, cross})
}

// original task: [TestTask.ProcessComplexStruct]
func ProcessComplexStruct[ComplexStruct_0 _T19](data ComplexStruct_0) *RemoteFunc[*Future1[ComplexStruct]] {
	return NewRemoteFunc[*Future1[ComplexStruct]]("ProcessComplexStruct", []any{data})
}

// original task: [TestTask.ProcessSliceOfStructs]
func ProcessSliceOfStructs[sliceOfComplexStruct_0 _T20](structs sliceOfComplexStruct_0) *RemoteFunc[*Future1[[]ComplexStruct]] {
	return NewRemoteFunc[*Future1[[]ComplexStruct]]("ProcessSliceOfStructs", []any{structs})
}

// original task: [TestTask.ProcessMap]
func ProcessMap[mapstringToint_0 _T18](data mapstringToint_0) *RemoteFunc[*Future1[map[string]int]] {
	return NewRemoteFunc[*Future1[map[string]int]]("ProcessMap", []any{data})
}

// Test concurrent execution and ObjectRef chaining
// original task: [TestTask.SlowAdd]
func SlowAdd[int_0 _T9, int_1 _T9](a int_0, b int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("SlowAdd", []any{a, b})
}

// original task: [TestTask.SlowMultiply]
func SlowMultiply[int_0 _T9, int_1 _T9](a int_0, b int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("SlowMultiply", []any{a, b})
}

// original task: [TestTask.CombineResults]
func CombineResults[int_0 _T9, int_1 _T9, int_2 _T9](x int_0, y int_1, z int_2) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("CombineResults", []any{x, y, z})
}

// original task: [TestTask.ComputeSum]
func ComputeSum[sliceOfint_0 _T21](numbers sliceOfint_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("ComputeSum", []any{numbers})
}

// original task: [TestTask.GenerateSequence]
func GenerateSequence[int_0 _T9, int_1 _T9](start int_0, end int_1) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("GenerateSequence", []any{start, end})
}

// Tasks for testing boundary conditions
// original task: [TestTask.EmptySliceTask]
func EmptySliceTask[sliceOfint_0 _T21](data sliceOfint_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("EmptySliceTask", []any{data})
}

// original task: [TestTask.NilMapTask]
func NilMapTask[mapstringToint_0 _T18](data mapstringToint_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("NilMapTask", []any{data})
}

// original task: [TestTask.ZeroValueTask]
func ZeroValueTask[string_0 _T15, int_1 _T9, float64_2 _T16, bool_3 _T14](s string_0, i int_1, f float64_2, b bool_3) *RemoteFunc[*Future1[map[string]interface{}]] {
	return NewRemoteFunc[*Future1[map[string]interface{}]]("ZeroValueTask", []any{s, i, f, b})
}

// original task: [TestTask.LargeStringTask]
func LargeStringTask[int_0 _T9](size int_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("LargeStringTask", []any{size})
}

// original task: [TestTask.DeepNestedStructTask]
func DeepNestedStructTask() *RemoteFunc[*Future1[map[string]interface{}]] {
	return NewRemoteFunc[*Future1[map[string]interface{}]]("DeepNestedStructTask", []any{})
}

// Tasks that test numeric edge cases
// original task: [TestTask.NumericBoundaryTask]
func NumericBoundaryTask[int_0 _T9, int_1 _T9, float64_2 _T16](maxInt int_0, minInt int_1, largeFloat float64_2) *RemoteFunc[*Future1[map[string]interface{}]] {
	return NewRemoteFunc[*Future1[map[string]interface{}]]("NumericBoundaryTask", []any{maxInt, minInt, largeFloat})
}

// original task: [TestTask.SlowIncrementerTask]
func SlowIncrementerTask[int_0 _T9, int_1 _T9, int_2 _T9](initial int_0, steps int_1, delayMs int_2) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("SlowIncrementerTask", []any{initial, steps, delayMs})
}

// Tasks for testing concurrency edge cases
// original task: [TestTask.SharedStateSimulator]
func SharedStateSimulator[int_0 _T9, int_1 _T9](id int_0, iterations int_1) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("SharedStateSimulator", []any{id, iterations})
}

// original task: [TestTask.MemoryLeakTest]
func MemoryLeakTest[int_0 _T9](allocations int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("MemoryLeakTest", []any{allocations})
}

// Test error handling and edge cases
// original task: [TestTask.TaskThatPanics]
func TaskThatPanics[string_0 _T15](message string_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("TaskThatPanics", []any{message})
}

// original task: [TestTask.DivideByZero]
func DivideByZero[int_0 _T9, int_1 _T9](a int_0, b int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("DivideByZero", []any{a, b})
}

// original task: [TestTask.TaskWithDelay]
func TaskWithDelay[int_0 _T9, string_1 _T15](delay int_0, value string_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("TaskWithDelay", []any{delay, value})
}

// original task: [TestTask.TaskThatReturnsError]
func TaskThatReturnsError[bool_0 _T14](shouldFail bool_0) *RemoteFunc[*Future2[string, error]] {
	return NewRemoteFunc[*Future2[string, error]]("TaskThatReturnsError", []any{shouldFail})
}

// original task: [TestTask.ProcessLargeData]
func ProcessLargeData[int_0 _T9](size int_0) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("ProcessLargeData", []any{size})
}

// original task: [TestTask.EmptyReturns]
func EmptyReturns() *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("EmptyReturns", []any{})
}

// original task: [TestTask.MultipleReturnValues]
func MultipleReturnValues[int_0 _T9, int_1 _T9](a int_0, b int_1) *RemoteFunc[*Future4[int, int, string, bool]] {
	return NewRemoteFunc[*Future4[int, int, string, bool]]("MultipleReturnValues", []any{a, b})
}

// original task: [TestTask.GenData]
func GenData[int_0 _T9](x int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("GenData", []any{x})
}

// original task: [TestTask.MultipleReturns2]
func MultipleReturns2[int_0 _T9, string_1 _T15](a int_0, b string_1) *RemoteFunc[*Future3[int, string, bool]] {
	return NewRemoteFunc[*Future3[int, string, bool]]("MultipleReturns2", []any{a, b})
}

// original task: [TestTask.ReturnSlice]
func ReturnSlice() *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("ReturnSlice", []any{})
}

// original task: [TestTask.ReturnMap]
func ReturnMap() *RemoteFunc[*Future1[map[string]int]] {
	return NewRemoteFunc[*Future1[map[string]int]]("ReturnMap", []any{})
}

// original task: [TestTask.Divide]
func Divide[int64_0 _T22, int64_1 _T22](a int64_0, b int64_1) *RemoteFunc[*Future2[int64, int64]] {
	return NewRemoteFunc[*Future2[int64, int64]]("Divide", []any{a, b})
}

// original task: [TestTask.NoReturnVal]
func NoReturnVal[int64_0 _T22, int64_1 _T22](a int64_0, b int64_1) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("NoReturnVal", []any{a, b})
}

// original task: [TestTask.Busy]
func Busy[string_0 _T15, time_Duration_1 _T4](name string_0, duration time_Duration_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("Busy", []any{name, duration})
}

// 传递自定义类型的slice
// original task: [TestTask.AddPointSlice]
func AddPointSlice[sliceOfPoint_0 _T23](ps sliceOfPoint_0) *RemoteFunc[*Future1[Point]] {
	return NewRemoteFunc[*Future1[Point]]("AddPointSlice", []any{ps})
}

// 2参数
// original task: [TestTask.Add2Points]
func Add2Points[Point_0 _T24, Point_1 _T24](p1 Point_0, p2 Point_1) *RemoteFunc[*Future1[Point]] {
	return NewRemoteFunc[*Future1[Point]]("Add2Points", []any{p1, p2})
}

// 可变参数
// original task: [TestTask.AddPointsVar]
func AddPointsVar[Point_0 _T24](ps ...Point_0) *RemoteFunc[*Future1[Point]] {
	return NewRemoteFunc[*Future1[Point]]("AddPointsVar", ExpandArgs([]any{}, ps))
}

// original task: [TestTask.MultipleReturns]
func MultipleReturns[any_0 _T25, any_1 _T25](arg1 any_0, arg2 any_1) *RemoteFunc[*Future2[any, any]] {
	return NewRemoteFunc[*Future2[any, any]]("MultipleReturns", []any{arg1, arg2})
}

// original task: [TestTask.SingleReturns]
func SingleReturns[any_0 _T25](arg any_0) *RemoteFunc[*Future1[any]] {
	return NewRemoteFunc[*Future1[any]]("SingleReturns", []any{arg})
}

// Simulate a data processing pipeline
// original task: [TestTask.DataIngestion]
func DataIngestion[int_0 _T9, int_1 _T9](batchId int_0, records int_1) *RemoteFunc[*Future1[[]DataRecord]] {
	return NewRemoteFunc[*Future1[[]DataRecord]]("DataIngestion", []any{batchId, records})
}

// original task: [TestTask.DataCleaning]
func DataCleaning[sliceOfDataRecord_0 _T26](records sliceOfDataRecord_0) *RemoteFunc[*Future1[[]DataRecord]] {
	return NewRemoteFunc[*Future1[[]DataRecord]]("DataCleaning", []any{records})
}

// original task: [TestTask.DataAggregation]
func DataAggregation[sliceOfDataRecord_0 _T26](cleanedData sliceOfDataRecord_0) *RemoteFunc[*Future1[AggregationResult]] {
	return NewRemoteFunc[*Future1[AggregationResult]]("DataAggregation", []any{cleanedData})
}

// original task: [TestTask.ReportGeneration]
func ReportGeneration[AggregationResult_0 _T27](aggregatedData AggregationResult_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("ReportGeneration", []any{aggregatedData})
}

// Simulate a machine learning workflow
// original task: [TestTask.DatasetSplit]
func DatasetSplit[sliceOfsliceOffloat64_0 _T28, float64_1 _T16](data sliceOfsliceOffloat64_0, trainRatio float64_1) *RemoteFunc[*Future1[DatasetSplitData]] {
	return NewRemoteFunc[*Future1[DatasetSplitData]]("DatasetSplit", []any{data, trainRatio})
}

// original task: [TestTask.ModelTraining]
func ModelTraining[sliceOfsliceOffloat64_0 _T28, int_1 _T9](trainData sliceOfsliceOffloat64_0, epochs int_1) *RemoteFunc[*Future1[ModelResult]] {
	return NewRemoteFunc[*Future1[ModelResult]]("ModelTraining", []any{trainData, epochs})
}

// original task: [TestTask.ModelEvaluation]
func ModelEvaluation[ModelResult_0 _T29, sliceOfsliceOffloat64_1 _T28](model ModelResult_0, testData sliceOfsliceOffloat64_1) *RemoteFunc[*Future1[EvaluationResult]] {
	return NewRemoteFunc[*Future1[EvaluationResult]]("ModelEvaluation", []any{model, testData})
}

// Simulate a distributed compute workflow
// original task: [TestTask.ComputeTask]
func ComputeTask[int_0 _T9, ComputeWorkload_1 _T30](taskId int_0, workload ComputeWorkload_1) *RemoteFunc[*Future1[ComputeResult]] {
	return NewRemoteFunc[*Future1[ComputeResult]]("ComputeTask", []any{taskId, workload})
}

// original task: [TestTask.ResultAggregator]
func ResultAggregator[sliceOfComputeResult_0 _T31](results sliceOfComputeResult_0) *RemoteFunc[*Future1[AggregatedResults]] {
	return NewRemoteFunc[*Future1[AggregatedResults]]("ResultAggregator", []any{results})
}

// Task that calls other remote tasks
// original task: [TestTask.CoordinatorTask]
func CoordinatorTask[int_0 _T9](taskCount int_0) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("CoordinatorTask", []any{taskCount})
}

// original task: [TestTask.WorkerTask]
func WorkerTask[int_0 _T9, int_1 _T9](id int_0, multiplier int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("WorkerTask", []any{id, multiplier})
}

// Task that creates and uses actors
// original task: [TestTask.ActorCoordinatorTask]
func ActorCoordinatorTask[string_0 _T15, sliceOfstring_1 _T17](actorName string_0, operations sliceOfstring_1) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("ActorCoordinatorTask", []any{actorName, operations})
}

// Task that chains multiple remote calls
// original task: [TestTask.ChainedTask]
func ChainedTask[int_0 _T9, int_1 _T9](initial int_0, depth int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("ChainedTask", []any{initial, depth})
}

// Task that uses Put and Get operations
// original task: [TestTask.DataSharingTask]
func DataSharingTask[sliceOfint_0 _T21](data sliceOfint_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("DataSharingTask", []any{data})
}

// original task: [TestTask.ProcessStoredData]
func ProcessStoredData[sliceOfint_0 _T21](data sliceOfint_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("ProcessStoredData", []any{data})
}

// Task that uses Wait functionality
// original task: [TestTask.BatchCoordinatorTask]
func BatchCoordinatorTask[int_0 _T9](batchSize int_0) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("BatchCoordinatorTask", []any{batchSize})
}

// original task: [TestTask.SlowWorkerTask]
func SlowWorkerTask[int_0 _T9, int_1 _T9](id int_0, delayMs int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("SlowWorkerTask", []any{id, delayMs})
}

// original task: [TestTask.ProcessStoredObject]
func ProcessStoredObject[StorageTestStruct_0 _T32](obj StorageTestStruct_0) *RemoteFunc[*Future1[StorageTestStruct]] {
	return NewRemoteFunc[*Future1[StorageTestStruct]]("ProcessStoredObject", []any{obj})
}

// original task: [TestTask.CombineStoredObjects]
func CombineStoredObjects[StorageTestStruct_0 _T32, StorageTestStruct_1 _T32](obj1 StorageTestStruct_0, obj2 StorageTestStruct_1) *RemoteFunc[*Future1[StorageTestStruct]] {
	return NewRemoteFunc[*Future1[StorageTestStruct]]("CombineStoredObjects", []any{obj1, obj2})
}

// original task: [TestTask.UseMultipleStoredObjects]
func UseMultipleStoredObjects[sliceOfStorageTestStruct_0 _T33](objs sliceOfStorageTestStruct_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("UseMultipleStoredObjects", []any{objs})
}

// original task: [TestTask.ProcessPrimitiveTypes]
func ProcessPrimitiveTypes[int_0 _T9, float64_1 _T16, string_2 _T15, bool_3 _T14](i int_0, f float64_1, s string_2, b bool_3) *RemoteFunc[*Future4[int, float64, string, bool]] {
	return NewRemoteFunc[*Future4[int, float64, string, bool]]("ProcessPrimitiveTypes", []any{i, f, s, b})
}

// Test performance and scalability scenarios
// original task: [TestTask.QuickTask]
func QuickTask[int_0 _T9](id int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("QuickTask", []any{id})
}

// original task: [TestTask.MediumTask]
func MediumTask[int_0 _T9, sliceOfint_1 _T21](id int_0, data sliceOfint_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("MediumTask", []any{id, data})
}

// original task: [TestTask.FibonacciTask]
func FibonacciTask[int_0 _T9](n int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("FibonacciTask", []any{n})
}

// original task: [TestTask.MatrixMultiplyRow]
func MatrixMultiplyRow[sliceOffloat64_0 _T34, sliceOfsliceOffloat64_1 _T28](rowA sliceOffloat64_0, matrixB sliceOfsliceOffloat64_1) *RemoteFunc[*Future1[[]float64]] {
	return NewRemoteFunc[*Future1[[]float64]]("MatrixMultiplyRow", []any{rowA, matrixB})
}

// original task: [TestTask.AggregateResults]
func AggregateResults[sliceOfsliceOffloat64_0 _T28](results sliceOfsliceOffloat64_0) *RemoteFunc[*Future1[[]float64]] {
	return NewRemoteFunc[*Future1[[]float64]]("AggregateResults", []any{results})
}

// original task: [TestTask.ReturnStruct]
func ReturnStruct() *RemoteFunc[*Future1[GoNode]] {
	return NewRemoteFunc[*Future1[GoNode]]("ReturnStruct", []any{})
}

// original task: [TestTask.Pid]
func Pid() *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Pid", []any{})
}

// original task: [TestTask.Echo]
func Echo[any_0 _T25](args ...any_0) *RemoteFunc[*Future1[[]any]] {
	return NewRemoteFunc[*Future1[[]any]]("Echo", ExpandArgs([]any{}, args))
}

// original task: [TestTask.Single]
func Single[any_0 _T25](arg any_0) *RemoteFunc[*Future1[any]] {
	return NewRemoteFunc[*Future1[any]]("Single", []any{arg})
}

// original task: [TestTask.Hello]
func Hello[string_0 _T15](name string_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("Hello", []any{name})
}

// original task: [TestTask.NoReturn]
func NoReturn[string_0 _T15](name string_0) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("NoReturn", []any{name})
}

// original task: [TestTask.BusySleep]
func BusySleep[int_0 _T9](second int_0) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("BusySleep", []any{second})
}

// original task: [TestTask.ProcessStructWithUnexportedFields]
func ProcessStructWithUnexportedFields[StructWithUnexportedFields_0 _T35](s StructWithUnexportedFields_0) *RemoteFunc[*Future1[StructWithUnexportedFields]] {
	return NewRemoteFunc[*Future1[StructWithUnexportedFields]]("ProcessStructWithUnexportedFields", []any{s})
}

// original task: [TestTask.ProcessLinkedList]
func ProcessLinkedList[pointerOfNode_0 _T36](head pointerOfNode_0) *RemoteFunc[*Future1[*Node]] {
	return NewRemoteFunc[*Future1[*Node]]("ProcessLinkedList", []any{head})
}

// original task: [TestTask.ProcessSelfReferencingStruct]
func ProcessSelfReferencingStruct[SelfReferencingStruct_0 _T37](s SelfReferencingStruct_0) *RemoteFunc[*Future1[SelfReferencingStruct]] {
	return NewRemoteFunc[*Future1[SelfReferencingStruct]]("ProcessSelfReferencingStruct", []any{s})
}

// Test channels (should not work well in distributed context)
// original task: [TestTask.ProcessChannel]
func ProcessChannel[chanOfint_0 _T38, int_1 _T9](ch chanOfint_0, val int_1) *RemoteFunc[*Future1[chan int]] {
	return NewRemoteFunc[*Future1[chan int]]("ProcessChannel", []any{ch, val})
}

// Test function types (should not serialize)
// original task: [TestTask.ProcessFunction]
func ProcessFunction[funcWithint_int_0 _T39, int_1 _T9](fn funcWithint_int_0, val int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("ProcessFunction", []any{fn, val})
}

// Test unsafe pointers (should fail)
// original task: [TestTask.ProcessUnsafePointer]
func ProcessUnsafePointer[unsafe_Pointer_0 _T40](ptr unsafe_Pointer_0) *RemoteFunc[*Future1[unsafe.Pointer]] {
	return NewRemoteFunc[*Future1[unsafe.Pointer]]("ProcessUnsafePointer", []any{ptr})
}

// Test very large slices (test memory limits)
// original task: [TestTask.ProcessVeryLargeSlice]
func ProcessVeryLargeSlice[int_0 _T9](size int_0) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("ProcessVeryLargeSlice", []any{size})
}

// Test nil slices vs empty slices
// original task: [TestTask.ProcessNilAndEmptySlices]
func ProcessNilAndEmptySlices[sliceOfint_0 _T21, sliceOfint_1 _T21](nilSlice sliceOfint_0, emptySlice sliceOfint_1) *RemoteFunc[*Future4[bool, bool, int, int]] {
	return NewRemoteFunc[*Future4[bool, bool, int, int]]("ProcessNilAndEmptySlices", []any{nilSlice, emptySlice})
}

// Test nil maps vs empty maps
// original task: [TestTask.ProcessNilAndEmptyMaps]
func ProcessNilAndEmptyMaps[mapstringToint_0 _T18, mapstringToint_1 _T18](nilMap mapstringToint_0, emptyMap mapstringToint_1) *RemoteFunc[*Future4[bool, bool, int, int]] {
	return NewRemoteFunc[*Future4[bool, bool, int, int]]("ProcessNilAndEmptyMaps", []any{nilMap, emptyMap})
}

// original task: [TestTask.ProcessStructWithMixedPointers]
func ProcessStructWithMixedPointers[StructWithMixedPointers_0 _T41](s StructWithMixedPointers_0) *RemoteFunc[*Future1[StructWithMixedPointers]] {
	return NewRemoteFunc[*Future1[StructWithMixedPointers]]("ProcessStructWithMixedPointers", []any{s})
}

// original task: [TestTask.ProcessComplexNestedWithInterface]
func ProcessComplexNestedWithInterface[ComplexNestedWithInterface_0 _T42](s ComplexNestedWithInterface_0) *RemoteFunc[*Future1[ComplexNestedWithInterface]] {
	return NewRemoteFunc[*Future1[ComplexNestedWithInterface]]("ProcessComplexNestedWithInterface", []any{s})
}

// Test arrays vs slices behavior
// original task: [TestTask.ProcessArraysAndSlices]
func ProcessArraysAndSlices[arr5Ofint_0 _T43, sliceOfint_1 _T21](arr arr5Ofint_0, slice sliceOfint_1) *RemoteFunc[*Future2[[5]int, []int]] {
	return NewRemoteFunc[*Future2[[5]int, []int]]("ProcessArraysAndSlices", []any{arr, slice})
}

// Test empty string vs nil string pointer
// original task: [TestTask.ProcessStringPointers]
func ProcessStringPointers[string_0 _T15, pointerOfstring_1 _T44, pointerOfstring_2 _T44](emptyStr string_0, nilStrPtr pointerOfstring_1, validStrPtr pointerOfstring_2) *RemoteFunc[*Future3[string, *string, *string]] {
	return NewRemoteFunc[*Future3[string, *string, *string]]("ProcessStringPointers", []any{emptyStr, nilStrPtr, validStrPtr})
}

// Test ray task options and configuration
// original task: [TestTask.CpuIntensiveTask]
func CpuIntensiveTask[int_0 _T9](iterations int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("CpuIntensiveTask", []any{iterations})
}

// original task: [TestTask.MemoryIntensiveTask]
func MemoryIntensiveTask[int_0 _T9](size int_0) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("MemoryIntensiveTask", []any{size})
}

// original task: [TestTask.ResourceTrackingTask]
func ResourceTrackingTask[string_0 _T15, int_1 _T9](taskId string_0, duration int_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("ResourceTrackingTask", []any{taskId, duration})
}

// original task: [TestTask.BatchTask]
func BatchTask[int_0 _T9, sliceOfstring_1 _T17](batchId int_0, items sliceOfstring_1) *RemoteFunc[*Future1[[]string]] {
	return NewRemoteFunc[*Future1[[]string]]("BatchTask", []any{batchId, items})
}

// Test basic types support
// original task: [TestTask.ProcessBasicTypes]
func ProcessBasicTypes[int_0 _T9, int32_1 _T45, int64_2 _T22, float32_3 _T46, float64_4 _T16, string_5 _T15, bool_6 _T14, byte_7 _T47, rune_8 _T48](intVal int_0, int32Val int32_1, int64Val int64_2, floatVal float32_3, float64Val float64_4, stringVal string_5, boolVal bool_6, byteVal byte_7, runeVal rune_8) *RemoteFunc[*Future9[int, int32, int64, float32, float64, string, bool, byte, rune]] {
	return NewRemoteFunc[*Future9[int, int32, int64, float32, float64, string, bool, byte, rune]]("ProcessBasicTypes", []any{intVal, int32Val, int64Val, floatVal, float64Val, stringVal, boolVal, byteVal, runeVal})
}

// Test slice and array types
// original task: [TestTask.ProcessSliceAndArray]
func ProcessSliceAndArray[sliceOfint_0 _T21, sliceOfstring_1 _T17, arr3Ofint_2 _T49](intSlice sliceOfint_0, stringSlice sliceOfstring_1, intArray arr3Ofint_2) *RemoteFunc[*Future3[[]int, []string, [3]int]] {
	return NewRemoteFunc[*Future3[[]int, []string, [3]int]]("ProcessSliceAndArray", []any{intSlice, stringSlice, intArray})
}

// Test map types
// original task: [TestTask.ProcessMaps]
func ProcessMaps[mapstringToint_0 _T18, mapintTostring_1 _T50](stringIntMap mapstringToint_0, intStringMap mapintTostring_1) *RemoteFunc[*Future2[map[string]int, map[int]string]] {
	return NewRemoteFunc[*Future2[map[string]int, map[int]string]]("ProcessMaps", []any{stringIntMap, intStringMap})
}

// Test pointer types (should work for non-nil pointers)
// original task: [TestTask.ProcessPointers]
func ProcessPointers[pointerOfint_0 _T51, pointerOfstring_1 _T44](intPtr pointerOfint_0, stringPtr pointerOfstring_1) *RemoteFunc[*Future2[*int, *string]] {
	return NewRemoteFunc[*Future2[*int, *string]]("ProcessPointers", []any{intPtr, stringPtr})
}

// original task: [TestTask.ProcessValidStruct]
func ProcessValidStruct[ValidStruct_0 _T52](s ValidStruct_0) *RemoteFunc[*Future1[ValidStruct]] {
	return NewRemoteFunc[*Future1[ValidStruct]]("ProcessValidStruct", []any{s})
}

// Test empty/zero values (should work)
// original task: [TestTask.ProcessEmptyValues]
func ProcessEmptyValues[string_0 _T15, int_1 _T9, sliceOfint_2 _T21, mapstringToint_3 _T18](emptyString string_0, zeroInt int_1, emptySlice sliceOfint_2, emptyMap mapstringToint_3) *RemoteFunc[*Future4[string, int, []int, map[string]int]] {
	return NewRemoteFunc[*Future4[string, int, []int, map[string]int]]("ProcessEmptyValues", []any{emptyString, zeroInt, emptySlice, emptyMap})
}

// Test channel types (should work but be careful with usage)
// original task: [TestTask.ProcessChannelType]
func ProcessChannelType[chanOfint_0 _T38](ch chanOfint_0) *RemoteFunc[*Future1[chan int]] {
	return NewRemoteFunc[*Future1[chan int]]("ProcessChannelType", []any{ch})
}

// Test function types (might not work well in distributed context)
// original task: [TestTask.ProcessFunctionType]
func ProcessFunctionType[funcWithint_int_0 _T39](fn funcWithint_int_0) *RemoteFunc[*Future1[func(int) int]] {
	return NewRemoteFunc[*Future1[func(int) int]]("ProcessFunctionType", []any{fn})
}

// original task: [TestTask.TaskExpectingNonNilPointer]
func TaskExpectingNonNilPointer[pointerOfint_0 _T51](ptr pointerOfint_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("TaskExpectingNonNilPointer", []any{ptr})
}

// original task: [TestTask.TaskWithInterfaceParam]
func TaskWithInterfaceParam[any_0 _T53](val any_0) *RemoteFunc[*Future1[interface{}]] {
	return NewRemoteFunc[*Future1[interface{}]]("TaskWithInterfaceParam", []any{val})
}

// original task: [TestTask.TaskWithStructContainingInterface]
func TaskWithStructContainingInterface[StructWithInterface_0 _T54](s StructWithInterface_0) *RemoteFunc[*Future1[StructWithInterface]] {
	return NewRemoteFunc[*Future1[StructWithInterface]]("TaskWithStructContainingInterface", []any{s})
}

// original task: [TestTask.TaskWithNilInStruct]
func TaskWithNilInStruct[StructWithNilPointer_0 _T55](s StructWithNilPointer_0) *RemoteFunc[*Future1[StructWithNilPointer]] {
	return NewRemoteFunc[*Future1[StructWithNilPointer]]("TaskWithNilInStruct", []any{s})
}

// original task: [TestTask.TaskWithMultipleInterfaceParams]
func TaskWithMultipleInterfaceParams[any_0 _T53, any_1 _T53, any_2 _T53](a any_0, b any_1, c any_2) *RemoteFunc[*Future3[interface{}, interface{}, interface{}]] {
	return NewRemoteFunc[*Future3[interface{}, interface{}, interface{}]]("TaskWithMultipleInterfaceParams", []any{a, b, c})
}

// original task: [TestTask.TaskWithMapContainingInterface]
func TaskWithMapContainingInterface[mapstringToany_0 _T11](m mapstringToany_0) *RemoteFunc[*Future1[map[string]interface{}]] {
	return NewRemoteFunc[*Future1[map[string]interface{}]]("TaskWithMapContainingInterface", []any{m})
}

// original task: [TestTask.TaskWithSliceContainingInterface]
func TaskWithSliceContainingInterface[sliceOfany_0 _T10](s sliceOfany_0) *RemoteFunc[*Future1[[]interface{}]] {
	return NewRemoteFunc[*Future1[[]interface{}]]("TaskWithSliceContainingInterface", []any{s})
}

// original task: [TestTask.TaskWithNestedStructContainingInterface]
func TaskWithNestedStructContainingInterface[NestedStructWithInterface_0 _T56](nested NestedStructWithInterface_0) *RemoteFunc[*Future1[NestedStructWithInterface]] {
	return NewRemoteFunc[*Future1[NestedStructWithInterface]]("TaskWithNestedStructContainingInterface", []any{nested})
}

// original task: [TestTask.TaskWithValidPointers]
func TaskWithValidPointers[StructWithValidPointers_0 _T57](s StructWithValidPointers_0) *RemoteFunc[*Future1[StructWithValidPointers]] {
	return NewRemoteFunc[*Future1[StructWithValidPointers]]("TaskWithValidPointers", []any{s})
}

// original task: [TestTask.TaskWithValidMap]
func TaskWithValidMap[mapstringTostring_0 _T58](m mapstringTostring_0) *RemoteFunc[*Future1[map[string]string]] {
	return NewRemoteFunc[*Future1[map[string]string]]("TaskWithValidMap", []any{m})
}

// original task: [TestTask.TaskWithValidSlice]
func TaskWithValidSlice[sliceOfstring_0 _T17](s sliceOfstring_0) *RemoteFunc[*Future1[[]string]] {
	return NewRemoteFunc[*Future1[[]string]]("TaskWithValidSlice", []any{s})
}

type ActorStatefulActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.StatefulActor]
func NewStatefulActor[int_0 _T9](initialValue int_0) *RemoteActor[ActorStatefulActor] {
	return NewRemoteActor[ActorStatefulActor]("StatefulActor", []any{initialValue})
}

// original actor method: [*StatefulActor.GetValue]
func StatefulActor_GetValue(_actor *ActorStatefulActor) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("GetValue", []any{}, &_actor.ActorHandle)
}

// original actor method: [*StatefulActor.SetValue]
func StatefulActor_SetValue[int_0 _T9](_actor *ActorStatefulActor, newValue int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("SetValue", []any{newValue}, &_actor.ActorHandle)
}

// original actor method: [*StatefulActor.Add]
func StatefulActor_Add[int_0 _T9](_actor *ActorStatefulActor, delta int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Add", []any{delta}, &_actor.ActorHandle)
}

// original actor method: [*StatefulActor.GetHistory]
func StatefulActor_GetHistory(_actor *ActorStatefulActor) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("GetHistory", []any{}, &_actor.ActorHandle)
}

// original actor method: [*StatefulActor.Reset]
func StatefulActor_Reset(_actor *ActorStatefulActor) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("Reset", []any{}, &_actor.ActorHandle)
}

type ActorComplexActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.ComplexActor]
func NewComplexActor[string_0 _T15](id string_0) *RemoteActor[ActorComplexActor] {
	return NewRemoteActor[ActorComplexActor]("ComplexActor", []any{id})
}

// original actor method: [*ComplexActor.IncrementCounter]
func ComplexActor_IncrementCounter[string_0 _T15, int_1 _T9](_actor *ActorComplexActor, name string_0, delta int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("IncrementCounter", []any{name, delta}, &_actor.ActorHandle)
}

// original actor method: [*ComplexActor.GetCounter]
func ComplexActor_GetCounter[string_0 _T15](_actor *ActorComplexActor, name string_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("GetCounter", []any{name}, &_actor.ActorHandle)
}

// original actor method: [*ComplexActor.AddItem]
func ComplexActor_AddItem[string_0 _T15](_actor *ActorComplexActor, item string_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("AddItem", []any{item}, &_actor.ActorHandle)
}

// original actor method: [*ComplexActor.GetItems]
func ComplexActor_GetItems(_actor *ActorComplexActor) *RemoteFunc[*Future1[[]string]] {
	return NewRemoteFunc[*Future1[[]string]]("GetItems", []any{}, &_actor.ActorHandle)
}

// original actor method: [*ComplexActor.GetAllCounters]
func ComplexActor_GetAllCounters(_actor *ActorComplexActor) *RemoteFunc[*Future1[map[string]int]] {
	return NewRemoteFunc[*Future1[map[string]int]]("GetAllCounters", []any{}, &_actor.ActorHandle)
}

// original actor method: [*ComplexActor.ProcessBatch]
func ComplexActor_ProcessBatch[sliceOfmapstringToany_0 _T59](_actor *ActorComplexActor, operations sliceOfmapstringToany_0) *RemoteFunc[*Future1[[]interface{}]] {
	return NewRemoteFunc[*Future1[[]interface{}]]("ProcessBatch", []any{operations}, &_actor.ActorHandle)
}

type ActorSlowActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.SlowActor]
func NewSlowActor[int_0 _T9](id int_0) *RemoteActor[ActorSlowActor] {
	return NewRemoteActor[ActorSlowActor]("SlowActor", []any{id})
}

// original actor method: [*SlowActor.SlowOperation]
func SlowActor_SlowOperation[int_0 _T9, string_1 _T15](_actor *ActorSlowActor, duration int_0, value string_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("SlowOperation", []any{duration, value}, &_actor.ActorHandle)
}

// original actor method: [*SlowActor.VerySlowOperation]
func SlowActor_VerySlowOperation[int_0 _T9](_actor *ActorSlowActor, duration int_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("VerySlowOperation", []any{duration}, &_actor.ActorHandle)
}

// original actor method: [*SlowActor.GetId]
func SlowActor_GetId(_actor *ActorSlowActor) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("GetId", []any{}, &_actor.ActorHandle)
}

type ActorErrorActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.ErrorActor]
func NewErrorActor[bool_0 _T14](shouldFail bool_0) *RemoteActor[ActorErrorActor] {
	return NewRemoteActor[ActorErrorActor]("ErrorActor", []any{shouldFail})
}

// original actor method: [*ErrorActor.MightFail]
func ErrorActor_MightFail[string_0 _T15](_actor *ActorErrorActor, message string_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("MightFail", []any{message}, &_actor.ActorHandle)
}

// original actor method: [*ErrorActor.ToggleFailure]
func ErrorActor_ToggleFailure(_actor *ActorErrorActor) *RemoteFunc[*Future1[bool]] {
	return NewRemoteFunc[*Future1[bool]]("ToggleFailure", []any{}, &_actor.ActorHandle)
}

// original actor method: [*ErrorActor.DivideByZero]
func ErrorActor_DivideByZero[int_0 _T9, int_1 _T9](_actor *ActorErrorActor, a1 int_0, b int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("DivideByZero", []any{a1, b}, &_actor.ActorHandle)
}

type ActorResourceActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.ResourceActor]
func NewResourceActor[int_0 _T9](size int_0) *RemoteActor[ActorResourceActor] {
	return NewRemoteActor[ActorResourceActor]("ResourceActor", []any{size})
}

// original actor method: [*ResourceActor.ComputeSum]
func ResourceActor_ComputeSum(_actor *ActorResourceActor) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("ComputeSum", []any{}, &_actor.ActorHandle)
}

// original actor method: [*ResourceActor.GetSize]
func ResourceActor_GetSize(_actor *ActorResourceActor) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("GetSize", []any{}, &_actor.ActorHandle)
}

type ActorErrorTest struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.ErrorTest]
func NewErrorTest() *RemoteActor[ActorErrorTest] {
	return NewRemoteActor[ActorErrorTest]("ErrorTest", []any{})
}

// original actor method: [*StatefulActor.GetValue]
func ErrorTest_GetValue(_actor *ActorErrorTest) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("GetValue", []any{}, &_actor.ActorHandle)
}

// original actor method: [*StatefulActor.SetValue]
func ErrorTest_SetValue[int_0 _T9](_actor *ActorErrorTest, newValue int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("SetValue", []any{newValue}, &_actor.ActorHandle)
}

// original actor method: [*StatefulActor.Add]
func ErrorTest_Add[int_0 _T9](_actor *ActorErrorTest, delta int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Add", []any{delta}, &_actor.ActorHandle)
}

// original actor method: [*StatefulActor.GetHistory]
func ErrorTest_GetHistory(_actor *ActorErrorTest) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("GetHistory", []any{}, &_actor.ActorHandle)
}

// original actor method: [*StatefulActor.Reset]
func ErrorTest_Reset(_actor *ActorErrorTest) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("Reset", []any{}, &_actor.ActorHandle)
}

type ActorAdvancedOptionsActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.AdvancedOptionsActor]
func NewAdvancedOptionsActor[string_0 _T15](id string_0) *RemoteActor[ActorAdvancedOptionsActor] {
	return NewRemoteActor[ActorAdvancedOptionsActor]("AdvancedOptionsActor", []any{id})
}

// original actor method: [*AdvancedOptionsActor.GetStatus]
func AdvancedOptionsActor_GetStatus(_actor *ActorAdvancedOptionsActor) *RemoteFunc[*Future1[map[string]interface{}]] {
	return NewRemoteFunc[*Future1[map[string]interface{}]]("GetStatus", []any{}, &_actor.ActorHandle)
}

// original actor method: [*AdvancedOptionsActor.ProcessWithDelay]
func AdvancedOptionsActor_ProcessWithDelay[int_0 _T9, string_1 _T15](_actor *ActorAdvancedOptionsActor, delayMs int_0, data string_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("ProcessWithDelay", []any{delayMs, data}, &_actor.ActorHandle)
}

// original actor method: [*AdvancedOptionsActor.MemoryIntensiveOperation]
func AdvancedOptionsActor_MemoryIntensiveOperation[int_0 _T9](_actor *ActorAdvancedOptionsActor, size int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("MemoryIntensiveOperation", []any{size}, &_actor.ActorHandle)
}

type ActorChainCallActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.ChainCallActor]
func NewChainCallActor[bool_0 _T14, string_1 _T15](cross bool_0, actorTypeName string_1) *RemoteActor[ActorChainCallActor] {
	return NewRemoteActor[ActorChainCallActor]("ChainCallActor", []any{cross, actorTypeName})
}

// original actor method: [*actor.ChainCall]
func ChainCallActor_ChainCall[sliceOfstring_0 _T17, int_1 _T9, int_2 _T9](_actor *ActorChainCallActor, nodeIds sliceOfstring_0, currIdx int_1, remainStep int_2) *RemoteFunc[*Future1[map[string]struct{}]] {
	return NewRemoteFunc[*Future1[map[string]struct{}]]("ChainCall", []any{nodeIds, currIdx, remainStep}, &_actor.ActorHandle)
}

type ActorEdgeCaseActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.EdgeCaseActor]
func NewEdgeCaseActor() *RemoteActor[ActorEdgeCaseActor] {
	return NewRemoteActor[ActorEdgeCaseActor]("EdgeCaseActor", []any{})
}

// original actor method: [*EdgeCaseActor.StoreNil]
func EdgeCaseActor_StoreNil[string_0 _T15](_actor *ActorEdgeCaseActor, key string_0) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("StoreNil", []any{key}, &_actor.ActorHandle)
}

// original actor method: [*EdgeCaseActor.GetStoredValue]
func EdgeCaseActor_GetStoredValue[string_0 _T15](_actor *ActorEdgeCaseActor, key string_0) *RemoteFunc[*Future1[interface{}]] {
	return NewRemoteFunc[*Future1[interface{}]]("GetStoredValue", []any{key}, &_actor.ActorHandle)
}

// original actor method: [*EdgeCaseActor.ProcessLargeArray]
func EdgeCaseActor_ProcessLargeArray[int_0 _T9](_actor *ActorEdgeCaseActor, size int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("ProcessLargeArray", []any{size}, &_actor.ActorHandle)
}

// original actor method: [*EdgeCaseActor.InterruptibleOperation]
func EdgeCaseActor_InterruptibleOperation[int_0 _T9](_actor *ActorEdgeCaseActor, duration int_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("InterruptibleOperation", []any{duration}, &_actor.ActorHandle)
}

// original actor method: [*EdgeCaseActor.GetCallHistory]
func EdgeCaseActor_GetCallHistory(_actor *ActorEdgeCaseActor) *RemoteFunc[*Future1[[]string]] {
	return NewRemoteFunc[*Future1[[]string]]("GetCallHistory", []any{}, &_actor.ActorHandle)
}

// original actor method: [*EdgeCaseActor.ClearHistory]
func EdgeCaseActor_ClearHistory(_actor *ActorEdgeCaseActor) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("ClearHistory", []any{}, &_actor.ActorHandle)
}

// original actor method: [*EdgeCaseActor.SimulateError]
func EdgeCaseActor_SimulateError[bool_0 _T14](_actor *ActorEdgeCaseActor, shouldError bool_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("SimulateError", []any{shouldError}, &_actor.ActorHandle)
}

type ActorResourceCleanupActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.ResourceCleanupActor]
func NewResourceCleanupActor() *RemoteActor[ActorResourceCleanupActor] {
	return NewRemoteActor[ActorResourceCleanupActor]("ResourceCleanupActor", []any{})
}

// original actor method: [*ResourceCleanupActor.AllocateResource]
func ResourceCleanupActor_AllocateResource[string_0 _T15](_actor *ActorResourceCleanupActor, name string_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("AllocateResource", []any{name}, &_actor.ActorHandle)
}

// original actor method: [*ResourceCleanupActor.GetResourceCount]
func ResourceCleanupActor_GetResourceCount(_actor *ActorResourceCleanupActor) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("GetResourceCount", []any{}, &_actor.ActorHandle)
}

// original actor method: [*ResourceCleanupActor.ReleaseAllResources]
func ResourceCleanupActor_ReleaseAllResources(_actor *ActorResourceCleanupActor) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("ReleaseAllResources", []any{}, &_actor.ActorHandle)
}

// original actor method: [*ResourceCleanupActor.Deactivate]
func ResourceCleanupActor_Deactivate(_actor *ActorResourceCleanupActor) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("Deactivate", []any{}, &_actor.ActorHandle)
}

type ActorCounter struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.Counter]
func NewCounter[int_0 _T9](n int_0) *RemoteActor[ActorCounter] {
	return NewRemoteActor[ActorCounter]("Counter", []any{n})
}

// original actor method: [*counter.Incr]
func Counter_Incr[int_0 _T9](_actor *ActorCounter, n int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Incr", []any{n}, &_actor.ActorHandle)
}

// original actor method: [*counter.Decr]
func Counter_Decr[int_0 _T9](_actor *ActorCounter, n int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Decr", []any{n}, &_actor.ActorHandle)
}

// original actor method: [*counter.Busy]
func Counter_Busy[time_Duration_0 _T4](_actor *ActorCounter, n time_Duration_0) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("Busy", []any{n}, &_actor.ActorHandle)
}

type ActorNewWorkflowCoordinator struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.NewWorkflowCoordinator]
func NewNewWorkflowCoordinator() *RemoteActor[ActorNewWorkflowCoordinator] {
	return NewRemoteActor[ActorNewWorkflowCoordinator]("NewWorkflowCoordinator", []any{})
}

// original actor method: [*WorkflowCoordinator.StartWorkflow]
func NewWorkflowCoordinator_StartWorkflow[string_0 _T15, WorkflowConfig_1 _T60](_actor *ActorNewWorkflowCoordinator, workflowId string_0, config WorkflowConfig_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("StartWorkflow", []any{workflowId, config}, &_actor.ActorHandle)
}

// original actor method: [*WorkflowCoordinator.CompleteWorkflow]
func NewWorkflowCoordinator_CompleteWorkflow[string_0 _T15, WorkflowResults_1 _T61](_actor *ActorNewWorkflowCoordinator, workflowId string_0, results WorkflowResults_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("CompleteWorkflow", []any{workflowId, results}, &_actor.ActorHandle)
}

// original actor method: [*WorkflowCoordinator.GetWorkflowStatus]
func NewWorkflowCoordinator_GetWorkflowStatus[string_0 _T15](_actor *ActorNewWorkflowCoordinator, workflowId string_0) *RemoteFunc[*Future1[WorkflowStatus]] {
	return NewRemoteFunc[*Future1[WorkflowStatus]]("GetWorkflowStatus", []any{workflowId}, &_actor.ActorHandle)
}

// original actor method: [*WorkflowCoordinator.ListWorkflows]
func NewWorkflowCoordinator_ListWorkflows(_actor *ActorNewWorkflowCoordinator) *RemoteFunc[*Future1[[]string]] {
	return NewRemoteFunc[*Future1[[]string]]("ListWorkflows", []any{}, &_actor.ActorHandle)
}

type ActorNewResourcePool struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.NewResourcePool]
func NewNewResourcePool[sliceOfstring_0 _T17](resourceNames sliceOfstring_0) *RemoteActor[ActorNewResourcePool] {
	return NewRemoteActor[ActorNewResourcePool]("NewResourcePool", []any{resourceNames})
}

// original actor method: [*ResourcePool.AcquireResource]
func NewResourcePool_AcquireResource(_actor *ActorNewResourcePool) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("AcquireResource", []any{}, &_actor.ActorHandle)
}

// original actor method: [*ResourcePool.ReleaseResource]
func NewResourcePool_ReleaseResource[string_0 _T15](_actor *ActorNewResourcePool, name string_0) *RemoteFunc[*Future1[bool]] {
	return NewRemoteFunc[*Future1[bool]]("ReleaseResource", []any{name}, &_actor.ActorHandle)
}

// original actor method: [*ResourcePool.GetStatus]
func NewResourcePool_GetStatus(_actor *ActorNewResourcePool) *RemoteFunc[*Future1[ResourceStatus]] {
	return NewRemoteFunc[*Future1[ResourceStatus]]("GetStatus", []any{}, &_actor.ActorHandle)
}

type ActorNewTaskCallingActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.NewTaskCallingActor]
func NewNewTaskCallingActor[int_0 _T9](id int_0) *RemoteActor[ActorNewTaskCallingActor] {
	return NewRemoteActor[ActorNewTaskCallingActor]("NewTaskCallingActor", []any{id})
}

// original actor method: [*TaskCallingActor.CallRemoteTask]
func NewTaskCallingActor_CallRemoteTask[string_0 _T15, int_1 _T9](_actor *ActorNewTaskCallingActor, taskName string_0, value int_1) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("CallRemoteTask", []any{taskName, value}, &_actor.ActorHandle)
}

// original actor method: [*TaskCallingActor.BatchCallTasks]
func NewTaskCallingActor_BatchCallTasks[int_0 _T9](_actor *ActorNewTaskCallingActor, count int_0) *RemoteFunc[*Future1[[]int]] {
	return NewRemoteFunc[*Future1[[]int]]("BatchCallTasks", []any{count}, &_actor.ActorHandle)
}

type ActorNewActorCallingActor struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.NewActorCallingActor]
func NewNewActorCallingActor[int_0 _T9](id int_0) *RemoteActor[ActorNewActorCallingActor] {
	return NewRemoteActor[ActorNewActorCallingActor]("NewActorCallingActor", []any{id})
}

// original actor method: [*ActorCallingActor.CallOtherActor]
func NewActorCallingActor_CallOtherActor[string_0 _T15, string_1 _T15, int_2 _T9](_actor *ActorNewActorCallingActor, actorName string_0, methodName string_1, value int_2) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("CallOtherActor", []any{actorName, methodName, value}, &_actor.ActorHandle)
}

type ActorGoNewCounter struct {
	ray.ActorHandle
}

// original actor constructor: [ActorFactories.GoNewCounter]
func NewGoNewCounter[int_0 _T9](n int_0) *RemoteActor[ActorGoNewCounter] {
	return NewRemoteActor[ActorGoNewCounter]("GoNewCounter", []any{n})
}

// original actor method: [*cnt.Incr]
func GoNewCounter_Incr[int_0 _T9](_actor *ActorGoNewCounter, n int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Incr", []any{n}, &_actor.ActorHandle)
}

// original actor method: [*cnt.Decr]
func GoNewCounter_Decr[int_0 _T9](_actor *ActorGoNewCounter, n int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Decr", []any{n}, &_actor.ActorHandle)
}

// original actor method: [*cnt.Pid]
func GoNewCounter_Pid(_actor *ActorGoNewCounter) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Pid", []any{}, &_actor.ActorHandle)
}

// original actor method: [*cnt.Echo]
func GoNewCounter_Echo[any_0 _T25](_actor *ActorGoNewCounter, args ...any_0) *RemoteFunc[*Future1[[]any]] {
	return NewRemoteFunc[*Future1[[]any]]("Echo", ExpandArgs([]any{}, args), &_actor.ActorHandle)
}

// original actor method: [*cnt.Single]
func GoNewCounter_Single[any_0 _T25](_actor *ActorGoNewCounter, arg any_0) *RemoteFunc[*Future1[any]] {
	return NewRemoteFunc[*Future1[any]]("Single", []any{arg}, &_actor.ActorHandle)
}

// original actor method: [*cnt.Hello]
func GoNewCounter_Hello[string_0 _T15](_actor *ActorGoNewCounter, name string_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("Hello", []any{name}, &_actor.ActorHandle)
}

// original actor method: [*cnt.NoReturn]
func GoNewCounter_NoReturn[string_0 _T15](_actor *ActorGoNewCounter, name string_0) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("NoReturn", []any{name}, &_actor.ActorHandle)
}

// original actor method: [*cnt.BusySleep]
func GoNewCounter_BusySleep[int_0 _T9](_actor *ActorGoNewCounter, second int_0) *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("BusySleep", []any{second}, &_actor.ActorHandle)
}

type _T0 interface {
	CustomInt | *Future1[CustomInt] | ray.SharedObject[CustomInt]
}

type _T1 interface {
	CustomString | *Future1[CustomString] | ray.SharedObject[CustomString]
}

type _T2 interface {
	CustomSlice | *Future1[CustomSlice] | ray.SharedObject[CustomSlice]
}

type _T3 interface {
	time.Time | *Future1[time.Time] | ray.SharedObject[time.Time]
}

type _T4 interface {
	time.Duration | *Future1[time.Duration] | ray.SharedObject[time.Duration]
}

type _T5 interface {
	OuterStruct | *Future1[OuterStruct] | ray.SharedObject[OuterStruct]
}

type _T6 interface {
	map[string]map[string]int | *Future1[map[string]map[string]int] | ray.SharedObject[map[string]map[string]int]
}

type _T7 interface {
	[][]string | *Future1[[][]string] | ray.SharedObject[[][]string]
}

type _T8 interface {
	map[string][]int | *Future1[map[string][]int] | ray.SharedObject[map[string][]int]
}

type _T9 interface {
	int | *Future1[int] | ray.SharedObject[int]
}

type _T10 interface {
	[]interface{} | *Future1[[]interface{}] | ray.SharedObject[[]interface{}]
}

type _T11 interface {
	map[string]interface{} | *Future1[map[string]interface{}] | ray.SharedObject[map[string]interface{}]
}

type _T12 interface {
	DeeplyNestedStruct | *Future1[DeeplyNestedStruct] | ray.SharedObject[DeeplyNestedStruct]
}

type _T13 interface {
	LargeStruct | *Future1[LargeStruct] | ray.SharedObject[LargeStruct]
}

type _T14 interface {
	bool | *Future1[bool] | ray.SharedObject[bool]
}

type _T15 interface {
	string | *Future1[string] | ray.SharedObject[string]
}

type _T16 interface {
	float64 | *Future1[float64] | ray.SharedObject[float64]
}

type _T17 interface {
	[]string | *Future1[[]string] | ray.SharedObject[[]string]
}

type _T18 interface {
	map[string]int | *Future1[map[string]int] | ray.SharedObject[map[string]int]
}

type _T19 interface {
	ComplexStruct | *Future1[ComplexStruct] | ray.SharedObject[ComplexStruct]
}

type _T20 interface {
	[]ComplexStruct | *Future1[[]ComplexStruct] | ray.SharedObject[[]ComplexStruct]
}

type _T21 interface {
	[]int | *Future1[[]int] | ray.SharedObject[[]int]
}

type _T22 interface {
	int64 | *Future1[int64] | ray.SharedObject[int64]
}

type _T23 interface {
	[]Point | *Future1[[]Point] | ray.SharedObject[[]Point]
}

type _T24 interface {
	Point | *Future1[Point] | ray.SharedObject[Point]
}

type _T25 interface {
	any | *Future1[any] | ray.SharedObject[any]
}

type _T26 interface {
	[]DataRecord | *Future1[[]DataRecord] | ray.SharedObject[[]DataRecord]
}

type _T27 interface {
	AggregationResult | *Future1[AggregationResult] | ray.SharedObject[AggregationResult]
}

type _T28 interface {
	[][]float64 | *Future1[[][]float64] | ray.SharedObject[[][]float64]
}

type _T29 interface {
	ModelResult | *Future1[ModelResult] | ray.SharedObject[ModelResult]
}

type _T30 interface {
	ComputeWorkload | *Future1[ComputeWorkload] | ray.SharedObject[ComputeWorkload]
}

type _T31 interface {
	[]ComputeResult | *Future1[[]ComputeResult] | ray.SharedObject[[]ComputeResult]
}

type _T32 interface {
	StorageTestStruct | *Future1[StorageTestStruct] | ray.SharedObject[StorageTestStruct]
}

type _T33 interface {
	[]StorageTestStruct | *Future1[[]StorageTestStruct] | ray.SharedObject[[]StorageTestStruct]
}

type _T34 interface {
	[]float64 | *Future1[[]float64] | ray.SharedObject[[]float64]
}

type _T35 interface {
	StructWithUnexportedFields | *Future1[StructWithUnexportedFields] | ray.SharedObject[StructWithUnexportedFields]
}

type _T36 interface {
	*Node | *Future1[*Node] | ray.SharedObject[*Node]
}

type _T37 interface {
	SelfReferencingStruct | *Future1[SelfReferencingStruct] | ray.SharedObject[SelfReferencingStruct]
}

type _T38 interface {
	chan int | *Future1[chan int] | ray.SharedObject[chan int]
}

type _T39 interface {
	func(int) int | *Future1[func(int) int] | ray.SharedObject[func(int) int]
}

type _T40 interface {
	unsafe.Pointer | *Future1[unsafe.Pointer] | ray.SharedObject[unsafe.Pointer]
}

type _T41 interface {
	StructWithMixedPointers | *Future1[StructWithMixedPointers] | ray.SharedObject[StructWithMixedPointers]
}

type _T42 interface {
	ComplexNestedWithInterface | *Future1[ComplexNestedWithInterface] | ray.SharedObject[ComplexNestedWithInterface]
}

type _T43 interface {
	[5]int | *Future1[[5]int] | ray.SharedObject[[5]int]
}

type _T44 interface {
	*string | *Future1[*string] | ray.SharedObject[*string]
}

type _T45 interface {
	int32 | *Future1[int32] | ray.SharedObject[int32]
}

type _T46 interface {
	float32 | *Future1[float32] | ray.SharedObject[float32]
}

type _T47 interface {
	byte | *Future1[byte] | ray.SharedObject[byte]
}

type _T48 interface {
	rune | *Future1[rune] | ray.SharedObject[rune]
}

type _T49 interface {
	[3]int | *Future1[[3]int] | ray.SharedObject[[3]int]
}

type _T50 interface {
	map[int]string | *Future1[map[int]string] | ray.SharedObject[map[int]string]
}

type _T51 interface {
	*int | *Future1[*int] | ray.SharedObject[*int]
}

type _T52 interface {
	ValidStruct | *Future1[ValidStruct] | ray.SharedObject[ValidStruct]
}

type _T53 interface {
	interface{} | *Future1[interface{}] | ray.SharedObject[interface{}]
}

type _T54 interface {
	StructWithInterface | *Future1[StructWithInterface] | ray.SharedObject[StructWithInterface]
}

type _T55 interface {
	StructWithNilPointer | *Future1[StructWithNilPointer] | ray.SharedObject[StructWithNilPointer]
}

type _T56 interface {
	NestedStructWithInterface | *Future1[NestedStructWithInterface] | ray.SharedObject[NestedStructWithInterface]
}

type _T57 interface {
	StructWithValidPointers | *Future1[StructWithValidPointers] | ray.SharedObject[StructWithValidPointers]
}

type _T58 interface {
	map[string]string | *Future1[map[string]string] | ray.SharedObject[map[string]string]
}

type _T59 interface {
	[]map[string]interface{} | *Future1[[]map[string]interface{}] | ray.SharedObject[[]map[string]interface{}]
}

type _T60 interface {
	WorkflowConfig | *Future1[WorkflowConfig] | ray.SharedObject[WorkflowConfig]
}

type _T61 interface {
	WorkflowResults | *Future1[WorkflowResults] | ray.SharedObject[WorkflowResults]
}
