// Code generated by goray. DO NOT EDIT.
//
// This file was generated by goray.
// It contains wrappers for the ray tasks and actors in this package.
//
// To regenerate this file, run:
//
//	goraygen <package-path>
package main

import (
	. "github.com/ray4go/go-ray/ray/generic"
)

type _rayTasks struct{}

var demoTasks = _rayTasks{}

func (_ _rayTasks) Devide(a int64, b int64) *RemoteFunc[*Future2[int64, int64]] {
	_ = (demo).Devide // help you to find the original method
	return NewRemoteFunc[*Future2[int64, int64]]("Devide", []any{a, b})
}
