// Code generated by goray. DO NOT EDIT.
//
// This file was generated by goray.
// It contains wrappers for the ray tasks and actors in this package.
//
// To regenerate this file, run:
//
//	goraygen <package-path>
package main

import (
	"time"

	. "github.com/ray4go/go-ray/ray/generic"
)

type _rayTasks struct{}

var demoTasks = _rayTasks{}

func (_ _rayTasks) Hello(name string) *RemoteFunc[*Future1[string]] {
	_ = (demo).Hello // help you to find the original method
	return NewRemoteFunc[*Future1[string]]("Hello", []any{name})
}

func (_ _rayTasks) Busy(name string, duration time.Duration) *RemoteFunc[*Future1[string]] {
	_ = (demo).Busy // help you to find the original method
	return NewRemoteFunc[*Future1[string]]("Busy", []any{name, duration})
}

func (_ _rayTasks) AddPointSlice(ps []Point) *RemoteFunc[*Future1[Point]] {
	_ = (demo).AddPointSlice // help you to find the original method
	return NewRemoteFunc[*Future1[Point]]("AddPointSlice", []any{ps})
}

func (_ _rayTasks) Add2Points(p1 Point, p2 Point) *RemoteFunc[*Future1[Point]] {
	_ = (demo).Add2Points // help you to find the original method
	return NewRemoteFunc[*Future1[Point]]("Add2Points", []any{p1, p2})
}

func (_ _rayTasks) AddPointsVar(ps ...Point) *RemoteFunc[*Future1[Point]] {
	_ = (demo).AddPointsVar // help you to find the original method
	return NewRemoteFunc[*Future1[Point]]("AddPointsVar", ExpandArgs([]any{}, ps))
}

func (_ _rayTasks) NoReturnVal(a int64, b int64) *RemoteFunc[*Future0] {
	_ = (demo).NoReturnVal // help you to find the original method
	return NewRemoteFunc[*Future0]("NoReturnVal", []any{a, b})
}

func (_ _rayTasks) MultiReturn(i int, s string) *RemoteFunc[*Future2[int, string]] {
	_ = (demo).MultiReturn // help you to find the original method
	return NewRemoteFunc[*Future2[int, string]]("MultiReturn", []any{i, s})
}
