// Code generated by goray. DO NOT EDIT.
//
// This file was generated by goray.
// It contains wrappers for the ray tasks and actors in this package.
//
// To regenerate this file, run:
//
//	goraygen <package-path>
package main

import (
	"time"

	"github.com/ray4go/go-ray/ray"
	. "github.com/ray4go/go-ray/ray/generic"
)

// original task: [Tasks.Echo]
func Echo[any_0 _T0](args ...any_0) *RemoteFunc[*Future1[[]any]] {
	return NewRemoteFunc[*Future1[[]any]]("Echo", ExpandArgs([]any{}, args))
}

// original task: [Tasks.Hello]
func Hello[string_0 _T1](name string_0) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("Hello", []any{name})
}

// original task: [Tasks.Busy]
func Busy[string_0 _T1, time_Duration_1 _T2](name string_0, duration time_Duration_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("Busy", []any{name, duration})
}

// original task: [Tasks.CallOtherTask]
func CallOtherTask[string_0 _T1, time_Duration_1 _T2](name string_0, duration time_Duration_1) *RemoteFunc[*Future1[string]] {
	return NewRemoteFunc[*Future1[string]]("CallOtherTask", []any{name, duration})
}

// no return value
// original task: [Tasks.NoReturnVal]
func NoReturnVal() *RemoteFunc[*Future0] {
	return NewRemoteFunc[*Future0]("NoReturnVal", []any{})
}

// multiple return values
// original task: [Tasks.MultiReturn]
func MultiReturn[int_0 _T3, string_1 _T1](i int_0, s string_1) *RemoteFunc[*Future2[int, string]] {
	return NewRemoteFunc[*Future2[int, string]]("MultiReturn", []any{i, s})
}

// custom struct can be used as parameter and return value
// original task: [Tasks.AddPoints]
func AddPoints[Point_0 _T4](ps ...Point_0) *RemoteFunc[*Future1[Point]] {
	return NewRemoteFunc[*Future1[Point]]("AddPoints", ExpandArgs([]any{}, ps))
}

type ActorCounter struct {
	ray.ActorHandle
}

// original actor constructor: [actors.Counter]
func NewCounter[int_0 _T3](n int_0) *RemoteActor[ActorCounter] {
	return NewRemoteActor[ActorCounter]("Counter", []any{n})
}

// original actor method: [*counter.Incr]
func Counter_Incr[int_0 _T3](_actor *ActorCounter, n int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Incr", []any{n}, &_actor.ActorHandle)
}

// original actor method: [*counter.Decr]
func Counter_Decr[int_0 _T3](_actor *ActorCounter, n int_0) *RemoteFunc[*Future1[int]] {
	return NewRemoteFunc[*Future1[int]]("Decr", []any{n}, &_actor.ActorHandle)
}

type _T0 interface {
	any | *Future1[any] | ray.SharedObject[any]
}

type _T1 interface {
	string | *Future1[string] | ray.SharedObject[string]
}

type _T2 interface {
	time.Duration | *Future1[time.Duration] | ray.SharedObject[time.Duration]
}

type _T3 interface {
	int | *Future1[int] | ray.SharedObject[int]
}

type _T4 interface {
	Point | *Future1[Point] | ray.SharedObject[Point]
}
